### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by jellywiz** [Zia123456/leaderboard#2]

**Comment by jellywiz** [comment]
Great job implementing so far, it looks great 💯

- No linter errors ✔️
- Descriptive ReadMe file ✔️
- Clean code ✔️
- Correct use of Gitflow ✔️

![AbsolutelyIncredibleJonnyCotaGIF](https://user-images.githubusercontent.com/83097009/202469138-5bd201b2-3a9d-4432-bb58-48058da48b6f.gif)

**Comment by AbeeraTahir** [comment]
## Hi @Zia123456, 

Great effort by you in completing this project. Keep it up! 👏 

## Highlights

No linter errors ✔️ 
Clean code ✔️ 
Implemented all project requirements ✔️ 

## Thank you
